### ISSUE TITLE
Add ability to auto-prune blockstore.db on startup

### ISSUE THREAD

**Issue by enlight** [loomnetwork/loomchain#1393]
We already have the `block-store purge` command in `clusterkit` that we use to create minimal jump starts, but we also need this feature integrated into loom nodes so external validators can easily constrain the disk space usage of their nodes. Unlike the `clusterkit` command the loom node should probably move the existing `blockstore.db` to `blockstore.db.bak` and then copy a subset of the most recent blocks to a new `blockstore.db` (it'll be up to ops to remove the `blockstore.db.bak` at some point).

The following settings should be added to `loom.yml` to control this new feature:
```yaml
BlockStore:
  PruneOnStartup: true # should default to false for now
  NumBlocksToRetain: 10000 # number of most recent blocks to retain when pruning
  PruneGraceFactor: 10 # skip pruning if less than 10% of NumBlocksToRetain will be pruned
```
`PruneGraceFactor` is intended to prevent pruning from kicking in if the node is being frequently restarted while ops are tweaking the config.
